from typing import Union

class Backend:
    @classmethod
    def command(cls, service: int, method: int, data: bytes) -> bytes: ...
    def db_command(self, data: bytes) -> bytes: ...
    def start_api_server(
        self, *, runtime_overrides: Union[dict, None] = None
    ) -> None: ...
    def stop_api_server(self) -> None: ...
    def api_server_file_config_status(self) -> tuple[Union[bool, None], bool]: ...

def buildhash() -> str: ...
def open_backend(data: bytes) -> Backend: ...
def initialize_logging(log_file: Union[str, None]) -> Backend: ...
def syncserver() -> None: ...
